language: java
jdk:
  - oraclejdk8
script: sudo apt-get install gtk
script: mvn install

after_success:
  - mvn clean test jacoco:report coveralls:report
after_failure: "cat /home/travis/build/ecsoya/coverage-demo/org.ecsoya.demos.coverage.test/target/work/data/.metadata/.log"